--Categorias
INSERT INTO categoria (id_categoria, nombre_categoria) VALUES
(1, 'Trainee'),
(2, 'Junior'),
(3, 'Semi Senior'),
(4, 'Senior'),
(5, 'Tech Lead');

--Departamentos
INSERT INTO departamento (id_departamento, nombre, descripcion) VALUES
(1, 'Recursos Humanos', 'Gestión de personal'),
(2, 'Dirección General', 'Supervisión y toma de decisiones estratégicas'),
(3, 'Finanzas y Contabilidad', 'Gestión financiera y contable de la empresa'),
(4, 'Marketing y Ventas', 'Promoción y ventas de productos o servicios'),
(5, 'Producción y Operaciones', 'Gestión de procesos productivos'),
(6, 'Tecnología de la Información (TI)', 'Gestión de sistemas y soporte técnico'),
(7, 'Logística', 'Distribución, almacenamiento y transporte');

--Puestos
INSERT INTO puesto (id_puesto, nombre) VALUES
(2, 'Arquitecto de Software'),
(3, 'DevOps'),
(4, 'QA Analyst'),
(5, 'Scrum Master'),
(6, 'Project Manager'),
(7, 'Product Owner'),
(8, 'Analista Funcional'),
(9, 'Backend Developer'),
(10, 'Frontend Developer'),
(11, 'Fullstack Developer'),
(12, 'Data Analyst'),
(13, 'Data Engineer'),
(14, 'Data Scientist'),
(15, 'UX/UI Designer'),
(16, 'CTO');

--Roles
INSERT INTO rol (
  id_rol, nombre, fecha_creacion, online_login, offline_login, ver_datos_personales,
  editar_datos_personales, ver_datos_laborales, agregar_datos_laborales, editar_datos_laborales,
  agregar_empleado, ver_registro_asistencia, ver_informacion_bancaria, editar_informacion_bancaria,
  ingresar_asistencia, ingresar_inasistencia, ver_historial_nominas, calcular_nomina_manualmente,
  calcular_nomina_automaticamente, agregar_concepto, agregar_departamento, agregar_puesto,
  agregar_categoria, agregar_salario_con_vigencia, ver_vista_previa_recibo_sueldo,
  descargar_recibo_sueldo, ver_reportes, cerrar_sesion, descripcion
) VALUES
(1, 'Empleado', '2025-06-01', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, 'Rol que corresponde al empleado comun, tiene permisos asociados a lectura y muy limitada escritura/modificacion'),
(2, 'Administrador_RRHH', '2025-06-01', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'El administrador de recursos humanos tiene todos los permisos de escritura/lectura/modificacion/actualizacion posibles'),
(3, 'Supervisor', '2025-06-01', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, 'El supervisor es el rol el cual tiene permisos de lectura y escritura pero mas que nada asociado a los empelados para poder monitorearlos correctamente'),
(4, 'Analista_de_datos', '2025-06-01', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, 'El analista de datos tiene los permisos de lectura y escritura parecidos a los del supervisor nomas que este esta mas enfocado a lo analitico, graficos, reportes de metricas en general');

--Bancos
INSERT INTO banco (codigo_banco, nombre) VALUES
('00007', 'BANCO DE GALICIA Y BUENOS AIRES S.A.U.'),
('00011', 'BANCO DE LA NACION ARGENTINA'),
('00014', 'BANCO DE LA PROVINCIA DE BUENOS AIRES'),
('00015', 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA'),
('00016', 'CITIBANK N.A.'),
('00017', 'BANCO BBVA ARGENTINA S.A.'),
('00020', 'BANCO DE LA PROVINCIA DE CORDOBA S.A.'),
('00027', 'BANCO SUPERVIELLE S.A.'),
('00029', 'BANCO DE LA CIUDAD DE BUENOS AIRES'),
('00034', 'BANCO PATAGONIA S.A.'),
('00044', 'BANCO HIPOTECARIO S.A.'),
('00045', 'BANCO DE SAN JUAN S.A.'),
('00065', 'BANCO MUNICIPAL DE ROSARIO'),
('00072', 'BANCO SANTANDER ARGENTINA S.A.'),
('00083', 'BANCO DEL CHUBUT S.A.'),
('00086', 'BANCO DE SANTA CRUZ S.A.'),
('00093', 'BANCO DE LA PAMPA SOCIEDAD DE ECONOMÍA M'),
('00094', 'BANCO DE CORRIENTES S.A.'),
('00097', 'BANCO PROVINCIA DEL NEUQUÉN SOCIEDAD ANÓ'),
('00131', 'BANK OF CHINA LIMITED SUCURSAL BUENOS AI'),
('00143', 'BRUBANK S.A.U.'),
('00147', 'BIBANK S.A.'),
('00150', 'BANCO GGAL SA'),
('00165', 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATIO'),
('00191', 'BANCO CREDICOOP COOPERATIVO LIMITADO'),
('00198', 'BANCO DE VALORES S.A.'),
('00247', 'BANCO ROELA S.A.'),
('00254', 'BANCO MARIVA S.A.'),
('00266', 'BNP PARIBAS'),
('00268', 'BANCO PROVINCIA DE TIERRA DEL FUEGO'),
('00269', 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGU'),
('00277', 'BANCO SAENZ S.A.'),
('00281', 'BANCO MERIDIAN S.A.'),
('00285', 'BANCO MACRO S.A.'),
('00299', 'BANCO COMAFI SOCIEDAD ANONIMA'),
('00300', 'BANCO DE INVERSION Y COMERCIO EXTERIOR S'),
('00301', 'BANCO PIANO S.A.'),
('00305', 'BANCO JULIO SOCIEDAD ANONIMA'),
('00309', 'BANCO RIOJA SOCIEDAD ANONIMA UNIPERSONAL'),
('00310', 'BANCO DEL SOL S.A.'),
('00311', 'NUEVO BANCO DEL CHACO S. A.'),
('00312', 'BANCO VOII S.A.'),
('00315', 'BANCO DE FORMOSA S.A.'),
('00319', 'BANCO CMF S.A.'),
('00321', 'BANCO DE SANTIAGO DEL ESTERO S.A.'),
('00322', 'BANCO INDUSTRIAL S.A.'),
('00330', 'NUEVO BANCO DE SANTA FE SOCIEDAD ANONIMA'),
('00331', 'BANCO CETELEM ARGENTINA S.A.'),
('00332', 'BANCO DE SERVICIOS FINANCIEROS S.A.'),
('00338', 'BANCO DE SERVICIOS Y TRANSACCIONES S.A.'),
('00339', 'RCI BANQUE S.A.'),
('00340', 'BACS BANCO DE CREDITO Y SECURITIZACION S'),
('00341', 'BANCO MASVENTAS S.A.'),
('00384', 'WILOBANK S.A.U.'),
('00386', 'NUEVO BANCO DE ENTRE RÍOS S.A.'),
('00389', 'BANCO COLUMBIA S.A.'),
('00426', 'BANCO BICA S.A.'),
('00431', 'BANCO COINAG S.A.'),
('00432', 'BANCO DE COMERCIO S.A.'),
('00435', 'BANCO SUCREDITO REGIONAL S.A.U.'),
('00448', 'BANCO DINO S.A.'),
('44077', 'COMPAÑIA FINANCIERA ARGENTINA S.A.'),
('44088', 'VOLKSWAGEN FINANCIAL SERVICES COMPAÑIA F'),
('44092', 'FCA COMPAÑIA FINANCIERA S.A.'),
('44093', 'GPAT COMPAÑIA FINANCIERA S.A.U.'),
('44094', 'MERCEDES-BENZ COMPAÑÍA FINANCIERA ARGENT'),
('44095', 'ROMBO COMPAÑÍA FINANCIERA S.A.'),
('44096', 'JOHN DEERE CREDIT COMPAÑÍA FINANCIERA S.'),
('44098', 'PSA FINANCE ARGENTINA COMPAÑÍA FINANCIER'),
('44099', 'TOYOTA COMPAÑÍA FINANCIERA DE ARGENTINA'),
('45030', 'NARANJA DIGITAL COMPAÑÍA FINANCIERA S.A.'),
('45056', 'MONTEMAR COMPAÑIA FINANCIERA S.A.'),
('45072', 'REBA COMPAÑIA FINANCIERA S.A.'),
('65203', 'CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.');